sudo: required

services:
    - docker

before_install:
    - docker build -t containerly/murmur:travis library/murmur
    - docker run -d -p 64738:64738 containerly/murmur:travis
    - docker build -t containerly/createrepo:travis library/createrepo

script:
  - docker ps | grep containerly/murmur:travis
  - docker run -it --rm containerly/createrepo:travis --version
